sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '0.10'
before_install:
- npm i -g npm@^2.0.0
- gem update --system
- gem install sass --version "=3.3.7"
- gem install compass --version "=0.12.3"
- npm install -g grunt-cli bower
- bower install
before_script:
- npm prune
after_success:
- npm run semantic-release
