sudo: false
language: node_js
node_js:
- 4
cache:
  directories:
  - node_modules
notifications:
  email: false
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm install -g bower
- bower install
before_script:
- npm prune
after_script:
- npm run semantic-release
